// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsrztqfrtldzhnwqwprk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcnp0cWZydGxkemhud3F3cHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODcwMzgsImV4cCI6MjA2Mjk2MzAzOH0.ken4ympPp8dcPrwrMB-hUkUwDauWUh4cTvzrvRsYja0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);